version: "3"

services:
  app:
    build: .
    container_name: desafio-guia-bolso
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    stdin_open: true
